name: peptimap-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - _r-mutex=1.0.1
  - argcomplete=3.1.2
  - argh=0.30.4
  - bioconductor-annotate=1.76.0
  - bioconductor-annotationdbi=1.60.0
  - bioconductor-biobase=2.58.0
  - bioconductor-biocfilecache=2.6.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-biocio=1.8.0
  - bioconductor-biocparallel=1.32.5
  - bioconductor-biomart=2.54.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-ctc=1.72.0
  - bioconductor-data-packages=20230718
  - bioconductor-delayedarray=0.24.0
  - bioconductor-deseq2=1.38.0
  - bioconductor-dexseq=1.44.0
  - bioconductor-edger=3.40.0
  - bioconductor-genefilter=1.80.0
  - bioconductor-genelendatabase=1.34.0
  - bioconductor-geneplotter=1.76.0
  - bioconductor-genomeinfodb=1.34.9
  - bioconductor-genomeinfodbdata=1.2.9
  - bioconductor-genomicalignments=1.34.0
  - bioconductor-genomicfeatures=1.50.2
  - bioconductor-genomicranges=1.50.0
  - bioconductor-go.db=3.16.0
  - bioconductor-goseq=1.50.0
  - bioconductor-iranges=2.32.0
  - bioconductor-keggrest=1.38.0
  - bioconductor-limma=3.54.0
  - bioconductor-matrixgenerics=1.10.0
  - bioconductor-qvalue=2.30.0
  - bioconductor-rhtslib=2.0.0
  - bioconductor-rsamtools=2.14.0
  - bioconductor-rtracklayer=1.58.0
  - bioconductor-s4vectors=0.36.0
  - bioconductor-summarizedexperiment=1.28.0
  - bioconductor-xvector=0.38.0
  - bioconductor-zlibbioc=1.44.0
  - biopython=1.81
  - boost-cpp=1.78.0
  - bowtie2=2.5.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - cctools_osx-64=973.0.1
  - certifi=2023.11.17
  - charset-normalizer=3.3.1
  - clang=16.0.1
  - clang-16=16.0.1
  - clang_osx-64=16.0.1
  - clangxx=16.0.1
  - clangxx_osx-64=16.0.1
  - click=8.1.7
  - colorama=0.4.6
  - compiler-rt=16.0.1
  - compiler-rt_osx-64=16.0.1
  - contourpy=1.1.1
  - curl=8.1.2
  - cycler=0.12.1
  - datasketch=1.6.4
  - exceptiongroup=1.1.3
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - gffutils=0.12
  - gfortran_impl_osx-64=11.4.0
  - gfortran_osx-64=11.4.0
  - glpk=5.0
  - gmap=2023.10.10
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - htseq=2.0.3
  - htslib=1.17
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.1.0
  - importlib_resources=6.1.0
  - iniconfig=2.0.0
  - isl=0.25
  - joblib=1.3.2
  - jq=1.5
  - kallisto=0.50.0
  - kiwisolver=1.4.5
  - kmer-jellyfish=2.3.0
  - krb5=1.20.1
  - lcms2=2.15
  - ld64_osx-64=609
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp16=16.0.1
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdb=6.2.32
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=4.8.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=11.4.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libiconv=1.17
  - libjemalloc=5.3.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.1
  - libnghttp2=1.55.1
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - llvm-tools=16.0.1
  - make=4.3
  - matplotlib-base=3.7.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - munkres=1.0.7
  - ncurses=6.4
  - numpy=1.24.4
  - openjdk=21.0.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.0.3
  - pandoc=3.1.3
  - pango=1.50.14
  - pcre2=10.40
  - perl=5.32.1
  - perl-constant=1.33
  - perl-db_file=1.858
  - perl-exporter=5.72
  - perl-file-util=4.201720
  - perl-lib=0.63
  - pillow=10.0.0
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=3.11.0
  - pluggy=1.3.0
  - pooch=1.8.0
  - pthread-stubs=0.4
  - pyfaidx=0.7.2.2
  - pyfastx=2.0.1
  - pyparsing=3.1.1
  - pysam=0.21.0
  - pysocks=1.7.1
  - pytest=7.4.3
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3.post1
  - pyvcf3=1.0.3
  - pyyaml=6.0.1
  - r-amap=0.8_19
  - r-ape=5.7_1
  - r-argparse=2.2.2
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.3
  - r-base64enc=0.1_3
  - r-bh=1.81.0_1
  - r-biasedurn=2.0.11
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-broom=1.0.5
  - r-bslib=0.5.1
  - r-cachem=1.0.8
  - r-callr=3.7.3
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-cluster=2.1.4
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-conflicted=1.2.0
  - r-cpp11=0.4.6
  - r-crayon=1.5.2
  - r-curl=5.0.1
  - r-data.table=1.14.8
  - r-dbi=1.1.3
  - r-dbplyr=2.4.0
  - r-digest=0.6.33
  - r-dplyr=1.1.3
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.22
  - r-fansi=1.0.5
  - r-farver=2.1.1
  - r-fastcluster=1.2.3
  - r-fastmap=1.1.1
  - r-fastmatch=1.1_4
  - r-filelock=1.0.2
  - r-findpython=1.0.8
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-fs=1.6.3
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.4.4
  - r-glue=1.6.2
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gplots=3.1.3
  - r-gtable=0.3.4
  - r-gtools=3.9.4
  - r-haven=2.5.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.6.1
  - r-httr=1.4.7
  - r-hwriter=1.3.2.1
  - r-ids=1.0.1
  - r-igraph=1.4.2
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.7
  - r-kernsmooth=2.23_22
  - r-knitr=1.45
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-lattice=0.22_5
  - r-lifecycle=1.0.3
  - r-locfit=1.5_9.8
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_1.1
  - r-matrixstats=1.0.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_0
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_163
  - r-openssl=2.1.1
  - r-phangorn=2.11.1
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-prettyunits=1.2.0
  - r-processx=3.8.2
  - r-progress=1.2.2
  - r-ps=1.7.5
  - r-purrr=1.0.2
  - r-quadprog=1.5_8
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.11
  - r-rcpparmadillo=0.12.6.4.0
  - r-rcurl=1.98_1.12
  - r-readr=2.1.4
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.0.2
  - r-reshape2=1.4.4
  - r-restfulr=0.0.15
  - r-rjson=0.2.21
  - r-rlang=1.1.1
  - r-rmarkdown=2.25
  - r-rsqlite=2.3.2
  - r-rstudioapi=0.15.0
  - r-rvest=1.0.3
  - r-sass=0.4.7
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-sm=2.2_5.7.1
  - r-snow=0.4_4
  - r-statmod=1.5.0
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-survival=3.5_7
  - r-sys=3.4.2
  - r-systemfonts=1.0.5
  - r-textshaping=0.3.6
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.2.0
  - r-tinytex=0.48
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.1_1
  - r-vctrs=0.6.4
  - r-vioplot=0.4.0
  - r-viridislite=0.4.2
  - r-vroom=1.6.4
  - r-withr=2.5.2
  - r-xfun=0.40
  - r-xml=3.99_0.14
  - r-xml2=1.3.3
  - r-xtable=1.8_4
  - r-yaml=2.3.7
  - r-zoo=1.8_12
  - readline=8.2
  - requests=2.31.0
  - salmon=1.10.2
  - samtools=1.18
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=68.2.2
  - sigtool=0.1.3
  - simplejson=3.19.2
  - six=1.16.0
  - tapi=1100.0.11
  - tbb=2021.10.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.1
  - trimmomatic=0.39
  - trinity=2.15.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - unicodedata2=15.1.0
  - urllib3=2.0.7
  - wheel=0.41.3
  - xmltodict=0.13.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.2.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
