import pandas as pd

# Test data was randomly generated
MOCK_FILE_CONTENT = """GQLDR
NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY
QIPCI
LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FNQGVRDQR
ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC
SHDTY
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FMRPCQFFHCWMFSMDDH"""

EXPECTED_RESULT_DF_DEDUPLICATED = pd.DataFrame(
    {
        "ids": [[0], [1], [2], [3], [4, 8], [5], [6], [7], [9]],
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "FMRPCQFFHCWMFSMDDH",
        ],
        "count": [1, 1, 1, 1, 2, 1, 1, 1, 1],
    }
).astype(dtype={"ids": "object", "sequence": "string", "count": "uint32"})

EXPECTED_RESULT_DF_BASIC = pd.DataFrame(
    {
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FMRPCQFFHCWMFSMDDH",
        ]
    }
).astype(dtype={"sequence": "string"})

EXPECTED_RESULT_INDEX = {
    "NCYQKAQ": [1],
    "CYQKAQH": [1],
    "YQKAQHL": [1],
    "QKAQHLY": [1],
    "KAQHLYT": [1],
    "AQHLYTP": [1],
    "QHLYTPE": [1],
    "HLYTPEG": [1],
    "LYTPEGR": [1],
    "YTPEGRK": [1],
    "TPEGRKG": [1],
    "PEGRKGM": [1],
    "EGRKGMV": [1],
    "GRKGMVH": [1],
    "RKGMVHL": [1],
    "KGMVHLT": [1],
    "GMVHLTW": [1],
    "MVHLTWD": [1],
    "VHLTWDR": [1],
    "HLTWDRT": [1],
    "LTWDRTV": [1],
    "TWDRTVL": [1],
    "WDRTVLP": [1],
    "DRTVLPP": [1],
    "RTVLPPP": [1],
    "TVLPPPC": [1],
    "VLPPPCM": [1],
    "LPPPCMD": [1],
    "PPPCMDI": [1],
    "PPCMDIV": [1],
    "PCMDIVD": [1],
    "CMDIVDR": [1],
    "MDIVDRH": [1],
    "DIVDRHR": [1],
    "IVDRHRS": [1],
    "VDRHRSS": [1],
    "DRHRSSR": [1],
    "RHRSSRY": [1],
    "LSVRCEV": [3],
    "SVRCEVQ": [3],
    "VRCEVQC": [3],
    "RCEVQCH": [3],
    "CEVQCHW": [3],
    "EVQCHWD": [3],
    "VQCHWDY": [3],
    "QCHWDYD": [3],
    "CHWDYDL": [3],
    "HWDYDLP": [3],
    "WDYDLPV": [3],
    "DYDLPVM": [3],
    "YDLPVMR": [3],
    "DLPVMRH": [3],
    "LPVMRHK": [3],
    "PVMRHKT": [3],
    "VMRHKTF": [3],
    "MRHKTFL": [3],
    "RHKTFLA": [3],
    "HKTFLAP": [3],
    "KTFLAPC": [3],
    "TFLAPCH": [3],
    "FLAPCHT": [3],
    "LAPCHTW": [3],
    "APCHTWM": [3],
    "YCYRSED": [4, 8],
    "CYRSEDL": [4, 8],
    "YRSEDLL": [4, 8],
    "RSEDLLK": [4, 8],
    "SEDLLKI": [4, 8],
    "EDLLKIS": [4, 8],
    "DLLKISQ": [4, 8],
    "LLKISQQ": [4, 8],
    "LKISQQC": [4, 8],
    "KISQQCA": [4, 8],
    "ISQQCAR": [4, 8],
    "SQQCARH": [4, 8],
    "QQCARHR": [4, 8],
    "QCARHRK": [4, 8],
    "CARHRKA": [4, 8],
    "ARHRKAQ": [4, 8],
    "RHRKAQP": [4, 8],
    "HRKAQPW": [4, 8],
    "RKAQPWE": [4, 8],
    "KAQPWET": [4, 8],
    "AQPWETY": [4, 8],
    "QPWETYV": [4, 8],
    "PWETYVC": [4, 8],
    "WETYVCI": [4, 8],
    "ETYVCIR": [4, 8],
    "TYVCIRT": [4, 8],
    "YVCIRTF": [4, 8],
    "VCIRTFT": [4, 8],
    "CIRTFTP": [4, 8],
    "IRTFTPH": [4, 8],
    "RTFTPHT": [4, 8],
    "TFTPHTM": [4, 8],
    "FTPHTMM": [4, 8],
    "TPHTMMH": [4, 8],
    "PHTMMHE": [4, 8],
    "FNQGVRD": [5],
    "NQGVRDQ": [5],
    "QGVRDQR": [5],
    "ISNVGQY": [6],
    "SNVGQYS": [6],
    "NVGQYSQ": [6],
    "VGQYSQM": [6],
    "GQYSQML": [6],
    "QYSQMLS": [6],
    "YSQMLSE": [6],
    "SQMLSEF": [6],
    "QMLSEFE": [6],
    "MLSEFEF": [6],
    "LSEFEFC": [6],
    "SEFEFCK": [6],
    "EFEFCKK": [6],
    "FEFCKKV": [6],
    "EFCKKVY": [6],
    "FCKKVYC": [6],
    "CKKVYCS": [6],
    "KKVYCSC": [6],
    "KVYCSCE": [6],
    "VYCSCEF": [6],
    "YCSCEFD": [6],
    "CSCEFDV": [6],
    "SCEFDVD": [6],
    "CEFDVDR": [6],
    "EFDVDRG": [6],
    "FDVDRGS": [6],
    "DVDRGSQ": [6],
    "VDRGSQI": [6],
    "DRGSQIC": [6],
    "RGSQICS": [6],
    "GSQICSD": [6],
    "SQICSDD": [6],
    "QICSDDH": [6],
    "ICSDDHV": [6],
    "CSDDHVW": [6],
    "SDDHVWS": [6],
    "DDHVWSP": [6],
    "DHVWSPK": [6],
    "HVWSPKK": [6],
    "VWSPKKS": [6],
    "WSPKKSP": [6],
    "SPKKSPK": [6],
    "PKKSPKM": [6],
    "KKSPKMC": [6],
    "FMRPCQF": [9],
    "MRPCQFF": [9],
    "RPCQFFH": [9],
    "PCQFFHC": [9],
    "CQFFHCW": [9],
    "QFFHCWM": [9],
    "FFHCWMF": [9],
    "FHCWMFS": [9],
    "HCWMFSM": [9],
    "CWMFSMD": [9],
    "WMFSMDD": [9],
    "MFSMDDH": [9],
}

EXPECTED_RESULT_INDEX_ISOLEUCINE_REPLACED = dict(
    [(kmer.replace("I", "L"), ids) for kmer, ids in EXPECTED_RESULT_INDEX.items()]
)
