import pandas as pd

# Test data was randomly generated
MOCK_FILE_CONTENT = """GQLDR
NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY
QIPCI
LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FNQGVRDQR
ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC
SHDTY
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FMRPCQFFHCWMFSMDDH"""

PROTEIN_GROUPS_MOCK_FILE_CONTENT = """GQLDR\tp1,p3
NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY\tp2
QIPCI\tp10,p20,p30
LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM\tp10,p20,p30
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE\tp4,p5,p6,p7,p8,p9
FNQGVRDQR\tp4,p5,p6,p7,p8,p9
ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC\tp10,p12,p13
SHDTY\tp4,p5,p6,p7,p8,p9
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE\tp5,p6,p7,p8,p9
FMRPCQFFHCWMFSMDDH\tp2"""

EXPECTED_RESULT_DF_DEDUPLICATED = pd.DataFrame(
    {
        "ids": [[0], [1], [2], [3], [4, 8], [5], [6], [7], [9]],
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "FMRPCQFFHCWMFSMDDH",
        ],
        "count": [1, 1, 1, 1, 2, 1, 1, 1, 1],
    }
).astype(dtype={"ids": "object", "sequence": "string", "count": "uint32"})

EXPECTED_RESULT_DF_BASIC = pd.DataFrame(
    {
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FMRPCQFFHCWMFSMDDH",
        ]
    }
).astype(dtype={"sequence": "string"})

EXPECTED_RESULT_INDEX = {
    "NCYQKAQ": [1],
    "CYQKAQH": [1],
    "YQKAQHL": [1],
    "QKAQHLY": [1],
    "KAQHLYT": [1],
    "AQHLYTP": [1],
    "QHLYTPE": [1],
    "HLYTPEG": [1],
    "LYTPEGR": [1],
    "YTPEGRK": [1],
    "TPEGRKG": [1],
    "PEGRKGM": [1],
    "EGRKGMV": [1],
    "GRKGMVH": [1],
    "RKGMVHL": [1],
    "KGMVHLT": [1],
    "GMVHLTW": [1],
    "MVHLTWD": [1],
    "VHLTWDR": [1],
    "HLTWDRT": [1],
    "LTWDRTV": [1],
    "TWDRTVL": [1],
    "WDRTVLP": [1],
    "DRTVLPP": [1],
    "RTVLPPP": [1],
    "TVLPPPC": [1],
    "VLPPPCM": [1],
    "LPPPCMD": [1],
    "PPPCMDI": [1],
    "PPCMDIV": [1],
    "PCMDIVD": [1],
    "CMDIVDR": [1],
    "MDIVDRH": [1],
    "DIVDRHR": [1],
    "IVDRHRS": [1],
    "VDRHRSS": [1],
    "DRHRSSR": [1],
    "RHRSSRY": [1],
    "LSVRCEV": [3],
    "SVRCEVQ": [3],
    "VRCEVQC": [3],
    "RCEVQCH": [3],
    "CEVQCHW": [3],
    "EVQCHWD": [3],
    "VQCHWDY": [3],
    "QCHWDYD": [3],
    "CHWDYDL": [3],
    "HWDYDLP": [3],
    "WDYDLPV": [3],
    "DYDLPVM": [3],
    "YDLPVMR": [3],
    "DLPVMRH": [3],
    "LPVMRHK": [3],
    "PVMRHKT": [3],
    "VMRHKTF": [3],
    "MRHKTFL": [3],
    "RHKTFLA": [3],
    "HKTFLAP": [3],
    "KTFLAPC": [3],
    "TFLAPCH": [3],
    "FLAPCHT": [3],
    "LAPCHTW": [3],
    "APCHTWM": [3],
    "YCYRSED": [4, 8],
    "CYRSEDL": [4, 8],
    "YRSEDLL": [4, 8],
    "RSEDLLK": [4, 8],
    "SEDLLKI": [4, 8],
    "EDLLKIS": [4, 8],
    "DLLKISQ": [4, 8],
    "LLKISQQ": [4, 8],
    "LKISQQC": [4, 8],
    "KISQQCA": [4, 8],
    "ISQQCAR": [4, 8],
    "SQQCARH": [4, 8],
    "QQCARHR": [4, 8],
    "QCARHRK": [4, 8],
    "CARHRKA": [4, 8],
    "ARHRKAQ": [4, 8],
    "RHRKAQP": [4, 8],
    "HRKAQPW": [4, 8],
    "RKAQPWE": [4, 8],
    "KAQPWET": [4, 8],
    "AQPWETY": [4, 8],
    "QPWETYV": [4, 8],
    "PWETYVC": [4, 8],
    "WETYVCI": [4, 8],
    "ETYVCIR": [4, 8],
    "TYVCIRT": [4, 8],
    "YVCIRTF": [4, 8],
    "VCIRTFT": [4, 8],
    "CIRTFTP": [4, 8],
    "IRTFTPH": [4, 8],
    "RTFTPHT": [4, 8],
    "TFTPHTM": [4, 8],
    "FTPHTMM": [4, 8],
    "TPHTMMH": [4, 8],
    "PHTMMHE": [4, 8],
    "FNQGVRD": [5],
    "NQGVRDQ": [5],
    "QGVRDQR": [5],
    "ISNVGQY": [6],
    "SNVGQYS": [6],
    "NVGQYSQ": [6],
    "VGQYSQM": [6],
    "GQYSQML": [6],
    "QYSQMLS": [6],
    "YSQMLSE": [6],
    "SQMLSEF": [6],
    "QMLSEFE": [6],
    "MLSEFEF": [6],
    "LSEFEFC": [6],
    "SEFEFCK": [6],
    "EFEFCKK": [6],
    "FEFCKKV": [6],
    "EFCKKVY": [6],
    "FCKKVYC": [6],
    "CKKVYCS": [6],
    "KKVYCSC": [6],
    "KVYCSCE": [6],
    "VYCSCEF": [6],
    "YCSCEFD": [6],
    "CSCEFDV": [6],
    "SCEFDVD": [6],
    "CEFDVDR": [6],
    "EFDVDRG": [6],
    "FDVDRGS": [6],
    "DVDRGSQ": [6],
    "VDRGSQI": [6],
    "DRGSQIC": [6],
    "RGSQICS": [6],
    "GSQICSD": [6],
    "SQICSDD": [6],
    "QICSDDH": [6],
    "ICSDDHV": [6],
    "CSDDHVW": [6],
    "SDDHVWS": [6],
    "DDHVWSP": [6],
    "DHVWSPK": [6],
    "HVWSPKK": [6],
    "VWSPKKS": [6],
    "WSPKKSP": [6],
    "SPKKSPK": [6],
    "PKKSPKM": [6],
    "KKSPKMC": [6],
    "FMRPCQF": [9],
    "MRPCQFF": [9],
    "RPCQFFH": [9],
    "PCQFFHC": [9],
    "CQFFHCW": [9],
    "QFFHCWM": [9],
    "FFHCWMF": [9],
    "FHCWMFS": [9],
    "HCWMFSM": [9],
    "CWMFSMD": [9],
    "WMFSMDD": [9],
    "MFSMDDH": [9],
}

EXPECTED_RESULT_INDEX_PROTEIN_GROUPS = {
    "NCYQKAQ": [0],
    "CYQKAQH": [0],
    "YQKAQHL": [0],
    "QKAQHLY": [0],
    "KAQHLYT": [0],
    "AQHLYTP": [0],
    "QHLYTPE": [0],
    "HLYTPEG": [0],
    "LYTPEGR": [0],
    "YTPEGRK": [0],
    "TPEGRKG": [0],
    "PEGRKGM": [0],
    "EGRKGMV": [0],
    "GRKGMVH": [0],
    "RKGMVHL": [0],
    "KGMVHLT": [0],
    "GMVHLTW": [0],
    "MVHLTWD": [0],
    "VHLTWDR": [0],
    "HLTWDRT": [0],
    "LTWDRTV": [0],
    "TWDRTVL": [0],
    "WDRTVLP": [0],
    "DRTVLPP": [0],
    "RTVLPPP": [0],
    "TVLPPPC": [0],
    "VLPPPCM": [0],
    "LPPPCMD": [0],
    "PPPCMDI": [0],
    "PPCMDIV": [0],
    "PCMDIVD": [0],
    "CMDIVDR": [0],
    "MDIVDRH": [0],
    "DIVDRHR": [0],
    "IVDRHRS": [0],
    "VDRHRSS": [0],
    "DRHRSSR": [0],
    "RHRSSRY": [0],
    "LSVRCEV": [1],
    "SVRCEVQ": [1],
    "VRCEVQC": [1],
    "RCEVQCH": [1],
    "CEVQCHW": [1],
    "EVQCHWD": [1],
    "VQCHWDY": [1],
    "QCHWDYD": [1],
    "CHWDYDL": [1],
    "HWDYDLP": [1],
    "WDYDLPV": [1],
    "DYDLPVM": [1],
    "YDLPVMR": [1],
    "DLPVMRH": [1],
    "LPVMRHK": [1],
    "PVMRHKT": [1],
    "VMRHKTF": [1],
    "MRHKTFL": [1],
    "RHKTFLA": [1],
    "HKTFLAP": [1],
    "KTFLAPC": [1],
    "TFLAPCH": [1],
    "FLAPCHT": [1],
    "LAPCHTW": [1],
    "APCHTWM": [1],
    "YCYRSED": [2, 4],
    "CYRSEDL": [2, 4],
    "YRSEDLL": [2, 4],
    "RSEDLLK": [2, 4],
    "SEDLLKI": [2, 4],
    "EDLLKIS": [2, 4],
    "DLLKISQ": [2, 4],
    "LLKISQQ": [2, 4],
    "LKISQQC": [2, 4],
    "KISQQCA": [2, 4],
    "ISQQCAR": [2, 4],
    "SQQCARH": [2, 4],
    "QQCARHR": [2, 4],
    "QCARHRK": [2, 4],
    "CARHRKA": [2, 4],
    "ARHRKAQ": [2, 4],
    "RHRKAQP": [2, 4],
    "HRKAQPW": [2, 4],
    "RKAQPWE": [2, 4],
    "KAQPWET": [2, 4],
    "AQPWETY": [2, 4],
    "QPWETYV": [2, 4],
    "PWETYVC": [2, 4],
    "WETYVCI": [2, 4],
    "ETYVCIR": [2, 4],
    "TYVCIRT": [2, 4],
    "YVCIRTF": [2, 4],
    "VCIRTFT": [2, 4],
    "CIRTFTP": [2, 4],
    "IRTFTPH": [2, 4],
    "RTFTPHT": [2, 4],
    "TFTPHTM": [2, 4],
    "FTPHTMM": [2, 4],
    "TPHTMMH": [2, 4],
    "PHTMMHE": [2, 4],
    "FNQGVRD": [2],
    "NQGVRDQ": [2],
    "QGVRDQR": [2],
    "ISNVGQY": [3],
    "SNVGQYS": [3],
    "NVGQYSQ": [3],
    "VGQYSQM": [3],
    "GQYSQML": [3],
    "QYSQMLS": [3],
    "YSQMLSE": [3],
    "SQMLSEF": [3],
    "QMLSEFE": [3],
    "MLSEFEF": [3],
    "LSEFEFC": [3],
    "SEFEFCK": [3],
    "EFEFCKK": [3],
    "FEFCKKV": [3],
    "EFCKKVY": [3],
    "FCKKVYC": [3],
    "CKKVYCS": [3],
    "KKVYCSC": [3],
    "KVYCSCE": [3],
    "VYCSCEF": [3],
    "YCSCEFD": [3],
    "CSCEFDV": [3],
    "SCEFDVD": [3],
    "CEFDVDR": [3],
    "EFDVDRG": [3],
    "FDVDRGS": [3],
    "DVDRGSQ": [3],
    "VDRGSQI": [3],
    "DRGSQIC": [3],
    "RGSQICS": [3],
    "GSQICSD": [3],
    "SQICSDD": [3],
    "QICSDDH": [3],
    "ICSDDHV": [3],
    "CSDDHVW": [3],
    "SDDHVWS": [3],
    "DDHVWSP": [3],
    "DHVWSPK": [3],
    "HVWSPKK": [3],
    "VWSPKKS": [3],
    "WSPKKSP": [3],
    "SPKKSPK": [3],
    "PKKSPKM": [3],
    "KKSPKMC": [3],
    "FMRPCQF": [0],
    "MRPCQFF": [0],
    "RPCQFFH": [0],
    "PCQFFHC": [0],
    "CQFFHCW": [0],
    "QFFHCWM": [0],
    "FFHCWMF": [0],
    "FHCWMFS": [0],
    "HCWMFSM": [0],
    "CWMFSMD": [0],
    "WMFSMDD": [0],
    "MFSMDDH": [0],
}

EXPECTED_RESULT_INDEX_ISOLEUCINE_REPLACED = dict(
    [(kmer.replace("I", "L"), ids) for kmer, ids in EXPECTED_RESULT_INDEX.items()]
)

EXPECTED_RESULT_INDEX_PROTEIN_GROUPS_ISOLEUCINE_REPLACED = dict(
    [
        (kmer.replace("I", "L"), ids)
        for kmer, ids in EXPECTED_RESULT_INDEX_PROTEIN_GROUPS.items()
    ]
)
