import pandas as pd

# Test data was randomly generated
MOCK_FILE_CONTENT = """GQLDR
NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY
QIPCI
LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FNQGVRDQR
ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC
SHDTY
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE
FMRPCQFFHCWMFSMDDH"""

PROTEIN_GROUPS_MOCK_FILE_CONTENT = """GQLDR\tp1,p3
NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY\tp2
QIPCI\tp10,p20,p30
LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM\tp10,p20,p30
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE\tp4,p5,p6,p7,p8,p9
FNQGVRDQR\tp4,p5,p6,p7,p8,p9
ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC\tp10,p12,p13
SHDTY\tp4,p5,p6,p7,p8,p9
YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE\tp5,p6,p7,p8,p9
FMRPCQFFHCWMFSMDDH\tp2"""

EXPECTED_RESULT_DF_DEDUPLICATED = pd.DataFrame(
    {
        "ids": [[0], [1], [2], [3], [4, 8], [5], [6], [7], [9]],
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "FMRPCQFFHCWMFSMDDH",
        ],
        "count": [1, 1, 1, 1, 2, 1, 1, 1, 1],
    }
).astype(dtype={"ids": "object", "sequence": "string", "count": "uint32"})

EXPECTED_RESULT_DF_BASIC = pd.DataFrame(
    {
        "sequence": [
            "GQLDR",
            "NCYQKAQHLYTPEGRKGMVHLTWDRTVLPPPCMDIVDRHRSSRY",
            "QIPCI",
            "LSVRCEVQCHWDYDLPVMRHKTFLAPCHTWM",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FNQGVRDQR",
            "ISNVGQYSQMLSEFEFCKKVYCSCEFDVDRGSQICSDDHVWSPKKSPKMC",
            "SHDTY",
            "YCYRSEDLLKISQQCARHRKAQPWETYVCIRTFTPHTMMHE",
            "FMRPCQFFHCWMFSMDDH",
        ]
    }
).astype(dtype={"sequence": "string"})

EXPECTED_RESULT_INDEX = {
    "NCYQKAQ": [0],
    "CYQKAQH": [0],
    "YQKAQHL": [0],
    "QKAQHLY": [0],
    "KAQHLYT": [0],
    "AQHLYTP": [0],
    "QHLYTPE": [0],
    "HLYTPEG": [0],
    "LYTPEGR": [0],
    "YTPEGRK": [0],
    "TPEGRKG": [0],
    "PEGRKGM": [0],
    "EGRKGMV": [0],
    "GRKGMVH": [0],
    "RKGMVHL": [0],
    "KGMVHLT": [0],
    "GMVHLTW": [0],
    "MVHLTWD": [0],
    "VHLTWDR": [0],
    "HLTWDRT": [0],
    "LTWDRTV": [0],
    "TWDRTVL": [0],
    "WDRTVLP": [0],
    "DRTVLPP": [0],
    "RTVLPPP": [0],
    "TVLPPPC": [0],
    "VLPPPCM": [0],
    "LPPPCMD": [0],
    "PPPCMDI": [0],
    "PPCMDIV": [0],
    "PCMDIVD": [0],
    "CMDIVDR": [0],
    "MDIVDRH": [0],
    "DIVDRHR": [0],
    "IVDRHRS": [0],
    "VDRHRSS": [0],
    "DRHRSSR": [0],
    "RHRSSRY": [0],
    "LSVRCEV": [1],
    "SVRCEVQ": [1],
    "VRCEVQC": [1],
    "RCEVQCH": [1],
    "CEVQCHW": [1],
    "EVQCHWD": [1],
    "VQCHWDY": [1],
    "QCHWDYD": [1],
    "CHWDYDL": [1],
    "HWDYDLP": [1],
    "WDYDLPV": [1],
    "DYDLPVM": [1],
    "YDLPVMR": [1],
    "DLPVMRH": [1],
    "LPVMRHK": [1],
    "PVMRHKT": [1],
    "VMRHKTF": [1],
    "MRHKTFL": [1],
    "RHKTFLA": [1],
    "HKTFLAP": [1],
    "KTFLAPC": [1],
    "TFLAPCH": [1],
    "FLAPCHT": [1],
    "LAPCHTW": [1],
    "APCHTWM": [1],
    "YCYRSED": [2, 5],
    "CYRSEDL": [2, 5],
    "YRSEDLL": [2, 5],
    "RSEDLLK": [2, 5],
    "SEDLLKI": [2, 5],
    "EDLLKIS": [2, 5],
    "DLLKISQ": [2, 5],
    "LLKISQQ": [2, 5],
    "LKISQQC": [2, 5],
    "KISQQCA": [2, 5],
    "ISQQCAR": [2, 5],
    "SQQCARH": [2, 5],
    "QQCARHR": [2, 5],
    "QCARHRK": [2, 5],
    "CARHRKA": [2, 5],
    "ARHRKAQ": [2, 5],
    "RHRKAQP": [2, 5],
    "HRKAQPW": [2, 5],
    "RKAQPWE": [2, 5],
    "KAQPWET": [2, 5],
    "AQPWETY": [2, 5],
    "QPWETYV": [2, 5],
    "PWETYVC": [2, 5],
    "WETYVCI": [2, 5],
    "ETYVCIR": [2, 5],
    "TYVCIRT": [2, 5],
    "YVCIRTF": [2, 5],
    "VCIRTFT": [2, 5],
    "CIRTFTP": [2, 5],
    "IRTFTPH": [2, 5],
    "RTFTPHT": [2, 5],
    "TFTPHTM": [2, 5],
    "FTPHTMM": [2, 5],
    "TPHTMMH": [2, 5],
    "PHTMMHE": [2, 5],
    "FNQGVRD": [3],
    "NQGVRDQ": [3],
    "QGVRDQR": [3],
    "ISNVGQY": [4],
    "SNVGQYS": [4],
    "NVGQYSQ": [4],
    "VGQYSQM": [4],
    "GQYSQML": [4],
    "QYSQMLS": [4],
    "YSQMLSE": [4],
    "SQMLSEF": [4],
    "QMLSEFE": [4],
    "MLSEFEF": [4],
    "LSEFEFC": [4],
    "SEFEFCK": [4],
    "EFEFCKK": [4],
    "FEFCKKV": [4],
    "EFCKKVY": [4],
    "FCKKVYC": [4],
    "CKKVYCS": [4],
    "KKVYCSC": [4],
    "KVYCSCE": [4],
    "VYCSCEF": [4],
    "YCSCEFD": [4],
    "CSCEFDV": [4],
    "SCEFDVD": [4],
    "CEFDVDR": [4],
    "EFDVDRG": [4],
    "FDVDRGS": [4],
    "DVDRGSQ": [4],
    "VDRGSQI": [4],
    "DRGSQIC": [4],
    "RGSQICS": [4],
    "GSQICSD": [4],
    "SQICSDD": [4],
    "QICSDDH": [4],
    "ICSDDHV": [4],
    "CSDDHVW": [4],
    "SDDHVWS": [4],
    "DDHVWSP": [4],
    "DHVWSPK": [4],
    "HVWSPKK": [4],
    "VWSPKKS": [4],
    "WSPKKSP": [4],
    "SPKKSPK": [4],
    "PKKSPKM": [4],
    "KKSPKMC": [4],
    "FMRPCQF": [6],
    "MRPCQFF": [6],
    "RPCQFFH": [6],
    "PCQFFHC": [6],
    "CQFFHCW": [6],
    "QFFHCWM": [6],
    "FFHCWMF": [6],
    "FHCWMFS": [6],
    "HCWMFSM": [6],
    "CWMFSMD": [6],
    "WMFSMDD": [6],
    "MFSMDDH": [6],
}

EXPECTED_RESULT_INDEX_PROTEIN_GROUPS = {
    "NCYQKAQ": [0],
    "CYQKAQH": [0],
    "YQKAQHL": [0],
    "QKAQHLY": [0],
    "KAQHLYT": [0],
    "AQHLYTP": [0],
    "QHLYTPE": [0],
    "HLYTPEG": [0],
    "LYTPEGR": [0],
    "YTPEGRK": [0],
    "TPEGRKG": [0],
    "PEGRKGM": [0],
    "EGRKGMV": [0],
    "GRKGMVH": [0],
    "RKGMVHL": [0],
    "KGMVHLT": [0],
    "GMVHLTW": [0],
    "MVHLTWD": [0],
    "VHLTWDR": [0],
    "HLTWDRT": [0],
    "LTWDRTV": [0],
    "TWDRTVL": [0],
    "WDRTVLP": [0],
    "DRTVLPP": [0],
    "RTVLPPP": [0],
    "TVLPPPC": [0],
    "VLPPPCM": [0],
    "LPPPCMD": [0],
    "PPPCMDI": [0],
    "PPCMDIV": [0],
    "PCMDIVD": [0],
    "CMDIVDR": [0],
    "MDIVDRH": [0],
    "DIVDRHR": [0],
    "IVDRHRS": [0],
    "VDRHRSS": [0],
    "DRHRSSR": [0],
    "RHRSSRY": [0],
    "LSVRCEV": [1],
    "SVRCEVQ": [1],
    "VRCEVQC": [1],
    "RCEVQCH": [1],
    "CEVQCHW": [1],
    "EVQCHWD": [1],
    "VQCHWDY": [1],
    "QCHWDYD": [1],
    "CHWDYDL": [1],
    "HWDYDLP": [1],
    "WDYDLPV": [1],
    "DYDLPVM": [1],
    "YDLPVMR": [1],
    "DLPVMRH": [1],
    "LPVMRHK": [1],
    "PVMRHKT": [1],
    "VMRHKTF": [1],
    "MRHKTFL": [1],
    "RHKTFLA": [1],
    "HKTFLAP": [1],
    "KTFLAPC": [1],
    "TFLAPCH": [1],
    "FLAPCHT": [1],
    "LAPCHTW": [1],
    "APCHTWM": [1],
    "YCYRSED": [2, 4],
    "CYRSEDL": [2, 4],
    "YRSEDLL": [2, 4],
    "RSEDLLK": [2, 4],
    "SEDLLKI": [2, 4],
    "EDLLKIS": [2, 4],
    "DLLKISQ": [2, 4],
    "LLKISQQ": [2, 4],
    "LKISQQC": [2, 4],
    "KISQQCA": [2, 4],
    "ISQQCAR": [2, 4],
    "SQQCARH": [2, 4],
    "QQCARHR": [2, 4],
    "QCARHRK": [2, 4],
    "CARHRKA": [2, 4],
    "ARHRKAQ": [2, 4],
    "RHRKAQP": [2, 4],
    "HRKAQPW": [2, 4],
    "RKAQPWE": [2, 4],
    "KAQPWET": [2, 4],
    "AQPWETY": [2, 4],
    "QPWETYV": [2, 4],
    "PWETYVC": [2, 4],
    "WETYVCI": [2, 4],
    "ETYVCIR": [2, 4],
    "TYVCIRT": [2, 4],
    "YVCIRTF": [2, 4],
    "VCIRTFT": [2, 4],
    "CIRTFTP": [2, 4],
    "IRTFTPH": [2, 4],
    "RTFTPHT": [2, 4],
    "TFTPHTM": [2, 4],
    "FTPHTMM": [2, 4],
    "TPHTMMH": [2, 4],
    "PHTMMHE": [2, 4],
    "FNQGVRD": [2],
    "NQGVRDQ": [2],
    "QGVRDQR": [2],
    "ISNVGQY": [3],
    "SNVGQYS": [3],
    "NVGQYSQ": [3],
    "VGQYSQM": [3],
    "GQYSQML": [3],
    "QYSQMLS": [3],
    "YSQMLSE": [3],
    "SQMLSEF": [3],
    "QMLSEFE": [3],
    "MLSEFEF": [3],
    "LSEFEFC": [3],
    "SEFEFCK": [3],
    "EFEFCKK": [3],
    "FEFCKKV": [3],
    "EFCKKVY": [3],
    "FCKKVYC": [3],
    "CKKVYCS": [3],
    "KKVYCSC": [3],
    "KVYCSCE": [3],
    "VYCSCEF": [3],
    "YCSCEFD": [3],
    "CSCEFDV": [3],
    "SCEFDVD": [3],
    "CEFDVDR": [3],
    "EFDVDRG": [3],
    "FDVDRGS": [3],
    "DVDRGSQ": [3],
    "VDRGSQI": [3],
    "DRGSQIC": [3],
    "RGSQICS": [3],
    "GSQICSD": [3],
    "SQICSDD": [3],
    "QICSDDH": [3],
    "ICSDDHV": [3],
    "CSDDHVW": [3],
    "SDDHVWS": [3],
    "DDHVWSP": [3],
    "DHVWSPK": [3],
    "HVWSPKK": [3],
    "VWSPKKS": [3],
    "WSPKKSP": [3],
    "SPKKSPK": [3],
    "PKKSPKM": [3],
    "KKSPKMC": [3],
    "FMRPCQF": [0],
    "MRPCQFF": [0],
    "RPCQFFH": [0],
    "PCQFFHC": [0],
    "CQFFHCW": [0],
    "QFFHCWM": [0],
    "FFHCWMF": [0],
    "FHCWMFS": [0],
    "HCWMFSM": [0],
    "CWMFSMD": [0],
    "WMFSMDD": [0],
    "MFSMDDH": [0],
}

EXPECTED_RESULT_INDEX_ISOLEUCINE_REPLACED = dict(
    [(kmer.replace("I", "L"), ids) for kmer, ids in EXPECTED_RESULT_INDEX.items()]
)

EXPECTED_RESULT_INDEX_PROTEIN_GROUPS_ISOLEUCINE_REPLACED = dict(
    [
        (kmer.replace("I", "L"), ids)
        for kmer, ids in EXPECTED_RESULT_INDEX_PROTEIN_GROUPS.items()
    ]
)

EXPECTED_PEPTIDE_MAPPING = [-1, 0, -1, 1, 2, 3, 4, -1, 5, 6]
EXPECTED_PEPTIDE_MAPPING_PROTEIN_GROUPS = [-1, 0, -1, 1, 2, 2, 3, -1, 4, 0]
